sudo: false
language: scala
scala: 2.12.4
script: sbt coverage test coverageReport
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app: connectorspace-meetup
  strategy: git
  on:
    repo: LoyolaChicagoCode/meetup-client-scala
