sudo: false
language: scala
scala: 2.12.4
script: sbt coverage test:test it:test coverageReport
after_success: bash <(curl -s https://codecov.io/bash)
before_deploy:
  - sbt stage
  - wget https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz
  - tar -xzf heroku.tar.gz
  - ./heroku-cli-v6.14.39-addc925-linux-x64/bin/heroku local &
  - sbt e2e:test
  - test_status=$?
  - ps -ef | grep heroku
  - pkill -f heroku
  - exit "$test_status"
deploy:
  provider: heroku
  app: connectorspace-meetup
  strategy: git
  on:
    repo: klaeufer/meetup-client-scala
  api_key:
    secure: B1xUXOY1zF6s6m9zPPThSjGBx0UrgOgqROiXGvSYKNbZs//KoveRxSCXDy6t+w5D1xd3xA9T5rEI6eH6mDvRsy4XRL0xVE++m6V40ekE7Y83S8c6CQ42yOXjUCX4YfhGncCtSQ9/PNJobCxSNb8r7jQX1g7xHUhVQ2wW6N25/RL4Dhy5zyUaaKXAukoWgPJqM11PfAgpK0DFrF3RO7GR2INmu+pHhzgAQFpGIBAgbLM71bAA5G2/AkOd4iZ/klmjAnU0NKUJRNwsmigN+SUoQklMj2m+CYSt4iCjD/RYwxlJeNSn9JqtViBIrjKxzQSGw6J22TBarR9MNt4ZDt1Hs17gSabFasQDT5moEEDHnEY+5+W1hrjVeXkj+x/O40bBEA//QHWwcg1DS60fSrJyxgwHTB5HZROvGzA6mOTsPXuRN0zHMaWiPUqKmhC7ThSga5pJiu7kDDaO/yaieJt0i6vDuDIUoGAOfKePWe96Ei6LSJR4o60ChCugzThJ8qAK7pyAI1jMprswT3YEDMbakuWlu3WQl+BPmnVM8nLr5Mxicb5TF3kRvW7glxCFU9luRKIhLzPNTgAzx/zZs/zs31bwsjlC1grJSBYo/LaSbTKYBhgE9BPDaOP1XIOviTqgl41zTyhG0WyHjmQh+CPlZQ88uqsH7hFyxF4XxnhyThk=
env:
  global:
    secure: NRpMyledDa2qmDoopDY6k1mfI5e3DyGzwkvxNieo2hIq51QAs1ZwllvFGajxO1SOLNS7YjJmWeh8f+7tW+INq+sumn7oET4dsGiLj4GRl1E45AfAiGv749BSC0xRsqN8hpZv3qtOPWunuDPeTBvULNSFxzKGXOKfKfSgwStFMRmabt3fOoAX2SS3q6iLw3X/h/HS2YkDutPZA1yfVy62xRHduPbbI/izzVHuQhCbaQ4IinHsdsh8T1SgMNgETdXQCSXADA+2PZpqKCrcyKvUC+1k8cWJ4FIW8nxXn+iVgxqs97N/MiU+JOGpXe0jDEie+qgDVT9WQ+aRkU4zUgv9fepBzXzTuk5JWfshupjpbL0Ze7sYnWvVDqbBT4lSXhZ/FzXsn6xkY5LsmmeEm2pmsGp5DdTUnP1QcCNsuxMZFxY650S8MrP0kk6BA5/8fLQqTOaXkJzxu5K7e7Y7R/0PKG3JbeMBtYBaevtwHaKqas87BZbLbf0CV3PkkhdF/c+JB03aXx+IkMUsLfYIbr0lrM+HcFtT5Da74ejgRODYEARCI23WucVblG5waiZb7sTurxGJXh/JAOgDyAovxLpjJsaUwQaFiRmf5RZHcxQJd70UpjcXiL83X/YH1RzQcGNKSn5aqFoLSD6IbhaXEfHDffrxOaIE1KkVVvLhBHOtJDM=
