sudo: false
language: scala
scala: 2.12.4
script: sbt coverage test coverageReport
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app: connectorspace-meetup
  strategy: git
  on:
    repo: klaeufer/meetup-client-scala
  api_key:
    secure: B1xUXOY1zF6s6m9zPPThSjGBx0UrgOgqROiXGvSYKNbZs//KoveRxSCXDy6t+w5D1xd3xA9T5rEI6eH6mDvRsy4XRL0xVE++m6V40ekE7Y83S8c6CQ42yOXjUCX4YfhGncCtSQ9/PNJobCxSNb8r7jQX1g7xHUhVQ2wW6N25/RL4Dhy5zyUaaKXAukoWgPJqM11PfAgpK0DFrF3RO7GR2INmu+pHhzgAQFpGIBAgbLM71bAA5G2/AkOd4iZ/klmjAnU0NKUJRNwsmigN+SUoQklMj2m+CYSt4iCjD/RYwxlJeNSn9JqtViBIrjKxzQSGw6J22TBarR9MNt4ZDt1Hs17gSabFasQDT5moEEDHnEY+5+W1hrjVeXkj+x/O40bBEA//QHWwcg1DS60fSrJyxgwHTB5HZROvGzA6mOTsPXuRN0zHMaWiPUqKmhC7ThSga5pJiu7kDDaO/yaieJt0i6vDuDIUoGAOfKePWe96Ei6LSJR4o60ChCugzThJ8qAK7pyAI1jMprswT3YEDMbakuWlu3WQl+BPmnVM8nLr5Mxicb5TF3kRvW7glxCFU9luRKIhLzPNTgAzx/zZs/zs31bwsjlC1grJSBYo/LaSbTKYBhgE9BPDaOP1XIOviTqgl41zTyhG0WyHjmQh+CPlZQ88uqsH7hFyxF4XxnhyThk=
